# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import fridasnippits.apps.frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20170527_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.TextField(default=fridasnippits.apps.frontend.models.generate_api_token, unique=True),
        ),
    ]
