# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0003_user_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hash",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
