# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0004_project_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
