# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0005_project_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set([("owner", "slug")]),
        ),
    ]
