# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0006_auto_20170528_0041"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
