# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0007_project_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="slug",
            new_name="project_slug",
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set([("owner", "project_slug")]),
        ),
    ]
