# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0008_auto_20170528_0146"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="liked_projects",
            field=models.ManyToManyField(
                related_name="liked_by", to="frontend.Project"
            ),
        ),
    ]
