# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0009_user_liked_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="likes",
        ),
    ]
