# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0010_remove_project_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="latest_version",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
